language: python

sudo: required

services:
  - docker

python:
  - 3.6

install:
  - pip install --upgrade setuptools
  - pip install codecov
  - pip install -r requirements_dev.txt

script:
  - flake8 myaioapp examples tests setup.py
  - bandit -r ./myaioapp ./examples setup.py
  - mypy myaioapp examples setup.py --ignore-missing-imports
  - py.test -v --cov-report term --cov-report html --cov myaioapp ./tests

after_success:
  codecov
