version: '3'
services:
  app:
    build: .
    ports:
      - '127.0.0.1:8080:80'
    environment:
      - HTTP_HOST=0.0.0.0
      - HTTP_PORT=80
      - DB_URL=postgres://postgres@postgres:5432/postgres
      - RABBIT_URL=amqp://guest:guest@rabbit:5672/
      - TRACER=zipkin
      - TRACER_URL=http://tracer:9411/
      - TRACER_SVC_NAME=myaioapp
      - METRICS=telegraf-influx
      - METRICS_URL=udp://telegraf:8094
      - METRICS_SVC_NAME=myaioapp_
    restart: on-failure
  rabbit:
    image: rabbitmq:latest
    ports:
      - '127.0.0.1:35672:5672'
    restart: on-failure
    #logging:
    #  driver: none
  postgres:
    image: postgres:latest
    ports:
      - '127.0.0.1:35432:5432'
    restart: on-failure
    #logging:
    #  driver: none
  tracer:
    image: jaegertracing/all-in-one:latest
    ports:
      - "127.0.0.1:39411:9411"
      - "127.0.0.1:36686:16686"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    #logging:
    #  driver: none
  influxdb:
    image: influxdb:latest
    environment:
      - INFLUXDB_DATA_ENGINE=tsm1
      - INFLUXDB_REPORTING_DISABLED=false
    volumes:
      - /var/lib/influxdb
    restart: on-failure
    #logging:
    #  driver: none
  telegraf:
    image: telegraf:latest
    volumes:
      - ./.docker.telegraf.conf:/etc/telegraf/telegraf.conf:ro
    restart: on-failure
    logging:
      driver: none
    #logging:
    #  driver: none
  grafana:
    # URL: http://127.0.0.1:10207/login
    # username: admin
    # password: admin
    #
    # Add data source:
    #     Type: InfluxDb
    #     URL: http://influxdb:8086/
    #     Database: telegraf
    #     User: telegraf
    #     Password: telegraf
    image: grafana/grafana:latest
    ports:
      - "127.0.0.1:33000:3000"
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource
    restart: on-failure
    #logging:
    #  driver: none
